networks:
  sentiric-net:
    # Bu dosya tek başına çalıştırıldığında ağı oluşturur.
    # Ana altyapı ile çalıştırıldığında, mevcut ağı kullanır.
    name: ${NETWORK_NAME:-sentiric-net}

volumes:
  postgres_data:
  rabbitmq_data:
  redis-data:
  qdrant_data:

services:

  postgres:
    image: postgres:16-alpine

    env_file:
      - ./.env.docker  

    ports: ["5432:5432"]

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../sentiric-config/postgres-init:/docker-entrypoint-initdb.d

    networks: [sentiric-net]
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  rabbitmq:
    image: rabbitmq:4.1.0-management-alpine

    env_file:
      - ./.env.docker    

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    # ports:
    #   - "${RABBITMQ_PORT:-5672}:${RABBITMQ_PORT:-5672}"
    #   - "15672:15672"
    networks:
      - sentiric-net

    
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    env_file:
      - ./.env.docker
    # ports:
    #   - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - sentiric-net
    volumes:
      - redis-data:/data

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest

    ports: ["${VECTOR_DB_PORT:-6333}:6333"]
    volumes: [qdrant_data:/qdrant/storage]
    networks: [sentiric-net]
    restart: always      

  task-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-service-api
    hostname: task-service-api
    env_file:
      - .env.docker # .env.docker kullanmak daha standart
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5003"]
    ports:
      - "${TASK_SERVICE_PORT:-5003}:5003"
    networks:
      - sentiric-net
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy # KRİTİK DEĞİŞİKLİK
      redis:
        condition: service_healthy # KRİTİK DEĞİŞİKLİK

  task-service-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-service-worker
    hostname: task-service-worker
    env_file:
      - .env.docker
    user: "sentiric_user"
    command: ["celery", "-A", "app.core.celery_app", "worker", "-l", "info"]
    networks:
      - sentiric-net
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy # KRİTİK DEĞİŞİKLİK
      redis:
        condition: service_healthy # KRİTİK DEĞİŞİKLİK

  task-service-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-service-beat
    hostname: task-service-beat
    env_file:
      - .env.docker
    user: "sentiric_user"
    command: ["celery", "-A", "app.core.celery_app", "beat", "-l", "info"]
    networks:
      - sentiric-net
    restart: unless-stopped
    depends_on:
      rabbitmq: { condition: service_healthy }
      redis: { condition: service_healthy }
      
  flower:
    image: mher/flower
    container_name: flower
    hostname: flower
    environment:
      - CELERY_BROKER_URL=${RABBITMQ_URL}
      - FLOWER_PORT=5555
    ports:
      - "5555:5555"
    networks:
      - sentiric-net
    restart: unless-stopped
    depends_on:
      # DÜZELTME: Hem worker'ın başlamasını hem de RabbitMQ'nun sağlıklı olmasını bekle.
      task-service-worker:
        condition: service_started
      rabbitmq:
        condition: service_healthy